version: '2'

services:
# flask:
#  build: ./flask
#  ports:
#   - 5000:5000
#  volumes:
#   - .:/code
 rabbitmq:
  image: rabbitmq
  ports:
   - 5672:5672

 flower:
  image: iserko/docker-celery-flower
  ports:
   - 5555:5555

 fenics:
  image: acc3/airfoiltest
  links:
   - rabbitmq
   - flower
  build: ./fenics
  ports:
   - 5000:5000
#   - 5555:5555
  tty: true
  restart: always
